use super::*;

pub(super) const DOMAIN_CLUSTERING_SYSTEM_PROMPT: &str =
    "You are analyzing a software repository to identify \
its functional (business) domains, not its technical/folder structure. Given per-module (folder) \
role summaries, and hints from any existing documentation, group every listed module into a small \
set of functional domains, optionally split into sub-domains when a domain is large enough to \
warrant it. Every module path given to you MUST appear in exactly one domain (or one of its \
sub-domains), copied verbatim; copy the root module's path as \"\" (empty string), never \".\" or \
\"/\". A parent module and one of its child modules may be assigned to different domains: a file \
belongs to whichever of its assigned ancestor modules is most specific (deepest), so it's fine to \
carve a sub-directory out into its own domain while leaving the parent's remaining files under the \
parent's domain. Reply with ONLY a single JSON object, no prose and no Markdown code fence, \
matching this shape: {\"domains\":[{\"slug\":\"kebab-case\",\"name\":\"...\",\"description\":\
\"...\",\"paths\":[\"...\"],\"sub_domains\":[{\"slug\":\"...\",\"name\":\"...\",\"description\":\
\"...\",\"paths\":[\"...\"]}]}]}. A domain's `paths` holds only the modules not better placed in \
one of its `sub_domains`.";

/// Added to the system prompt when the application surface (entities, entry
/// points) is available: the domains must read as business, not as layers.
pub(super) const BUSINESS_NAMING_ADDENDUM: &str =
    " The prompt also lists the application's business \
entities (from its data models) and its entry points grouped by resource. Use them to decide which \
modules belong together: name each domain after a business concept or activity (e.g. contract \
signing, company onboarding, billing), and put each module with the concept it serves most. Never \
name a domain after a technical layer or folder kind (presentation, services, models, controllers, \
views, helpers, utils, infrastructure, api, jobs).";

/// Words that name a technical layer rather than a business domain.
pub(super) const LAYER_WORDS: &[&str] = &[
    "presentation",
    "presenter",
    "presenters",
    "service",
    "services",
    "model",
    "models",
    "controller",
    "controllers",
    "view",
    "views",
    "helper",
    "helpers",
    "util",
    "utils",
    "utility",
    "utilities",
    "infrastructure",
    "api",
    "job",
    "jobs",
    "layer",
    "lib",
    "core",
    "common",
    "shared",
    "misc",
    "other",
];

/// Hash of what the clustering is derived from. Directory summaries are left
/// out on purpose: they are regenerated by the LLM on every run, so they
/// would change the hash while the files did not.
pub(super) fn clustering_fingerprint(
    repo_map: &RepoMap,
    existing_docs: &[ExistingDoc],
    surface: &Surface,
) -> String {
    let files = repo_map
        .files
        .iter()
        .map(|f| format!("{}\n{}", f.path.display(), f.role_summary));
    let docs = existing_docs
        .iter()
        .map(|d| format!("{}\n{}", d.path.display(), d.content));
    fingerprint(files.chain(docs).chain(surface.fingerprint_parts()))
}

/// Slugs of the domains and sub-domains whose name is made only of layer
/// words (`presentation-layer`, `services`): the technical split PLAN.md §6
/// warns about. Reported, not repaired.
pub(super) fn layer_named_domains(map: &DomainMap) -> Vec<String> {
    let is_layer = |slug: &str| {
        slug.split(|c: char| !c.is_alphanumeric())
            .filter(|w| !w.is_empty())
            .all(|w| LAYER_WORDS.contains(&w.to_lowercase().as_str()))
    };
    let mut found = Vec::new();
    for domain in &map.domains {
        if domain.slug != UNCATEGORIZED_SLUG && is_layer(&domain.slug) {
            found.push(domain.slug.clone());
        }
        for sub in &domain.sub_domains {
            if is_layer(&sub.slug) {
                found.push(format!("{}/{}", domain.slug, sub.slug));
            }
        }
    }
    found
}

pub(super) fn clustering_prompt(
    repo_map: &RepoMap,
    existing_docs: &[ExistingDoc],
    surface: &Surface,
) -> String {
    let mut prompt = String::new();
    if !surface.is_empty() {
        prompt.push_str(&surface.prompt_section());
        prompt.push('\n');
    }
    let _ = writeln!(prompt, "Modules:");
    for module in &repo_map.modules {
        let label = if module.path.as_os_str().is_empty() {
            String::new()
        } else {
            module.path.display().to_string()
        };
        let _ = writeln!(
            prompt,
            "- \"{label}\" ({} files): {}",
            module.file_count, module.role_summary
        );
    }

    if !existing_docs.is_empty() {
        let _ = writeln!(
            prompt,
            "\nExisting documentation (titles only, hints on business vocabulary):"
        );
        for doc in existing_docs {
            let title = doc
                .content
                .lines()
                .find(|l| !l.trim().is_empty())
                .unwrap_or("");
            let _ = writeln!(prompt, "- {}: {title}", doc.path.display());
        }
    }

    prompt
}
